import type { Country } from "@/lib/types";

const ZONE_TO_COUNTRY: Record<string, string> = {
  "America/Adak": "US",
  "America/Anchorage": "US",
  "America/Boise": "US",
  "America/Chicago": "US",
  "America/Denver": "US",
  "America/Detroit": "US",
  "America/Indiana/Indianapolis": "US",
  "America/Indiana/Knox": "US",
  "America/Indiana/Marengo": "US",
  "America/Indiana/Petersburg": "US",
  "America/Indiana/Tell_City": "US",
  "America/Indiana/Vevay": "US",
  "America/Indiana/Vincennes": "US",
  "America/Indiana/Winamac": "US",
  "America/Juneau": "US",
  "America/Kentucky/Louisville": "US",
  "America/Kentucky/Monticello": "US",
  "America/Los_Angeles": "US",
  "America/Menominee": "US",
  "America/Nome": "US",
  "America/North_Dakota/Beulah": "US",
  "America/North_Dakota/Center": "US",
  "America/North_Dakota/New_Salem": "US",
  "America/Phoenix": "US",
  "America/Sitka": "US",
  "America/Yakutat": "US",
  "Pacific/Honolulu": "US",
  "America/Creston": "CA",
  "America/Dawson": "CA",
  "America/Dawson_Creek": "CA",
  "America/Edmonton": "CA",
  "America/Fort_Nelson": "CA",
  "America/Glace_Bay": "CA",
  "America/Goose_Bay": "CA",
  "America/Halifax": "CA",
  "America/Moncton": "CA",
  "America/Nipigon": "CA",
  "America/Pangnirtung": "CA",
  "America/Regina": "CA",
  "America/Resolute": "CA",
  "America/St_Johns": "CA",
  "America/Swift_Current": "CA",
  "America/Thunder_Bay": "CA",
  "America/Vancouver": "CA",
  "America/Whitehorse": "CA",
  "America/Winnipeg": "CA",
  "America/Yellowknife": "CA",
  "America/Bahia_Banderas": "MX",
  "America/Cancun": "MX",
  "America/Chihuahua": "MX",
  "America/Ciudad_Juarez": "MX",
  "America/Hermosillo": "MX",
  "America/Mazatlan": "MX",
  "America/Merida": "MX",
  "America/Monterrey": "MX",
  "America/Ojinaga": "MX",
  "America/Tijuana": "MX",
  "America/Araguaina": "BR",
  "America/Bahia": "BR",
  "America/Belem": "BR",
  "America/Boa_Vista": "BR",
  "America/Campo_Grande": "BR",
  "America/Cuiaba": "BR",
  "America/Eirunepe": "BR",
  "America/Fortaleza": "BR",
  "America/Maceio": "BR",
  "America/Manaus": "BR",
  "America/Noronha": "BR",
  "America/Porto_Velho": "BR",
  "America/Recife": "BR",
  "America/Rio_Branco": "BR",
  "America/Santarem": "BR",
  "Antarctica/Macquarie": "AU",
  "Australia/Adelaide": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Broken_Hill": "AU",
  "Australia/Darwin": "AU",
  "Australia/Eucla": "AU",
  "Australia/Hobart": "AU",
  "Australia/Lindeman": "AU",
  "Australia/Lord_Howe": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Perth": "AU",
  "America/Punta_Arenas": "CL",
  "Pacific/Easter": "CL",
  "Atlantic/Canary": "ES",
  "Europe/Ceuta": "ES",
  "Atlantic/Azores": "PT",
  "Europe/Madeira": "PT",
  "Pacific/Chatham": "NZ",
  "Pacific/Galapagos": "EC",
  "Asia/Jayapura": "ID",
  "Asia/Makassar": "ID",
  "Asia/Pontianak": "ID",
  "Europe/Kaliningrad": "RU",
  "Europe/Kirov": "RU",
  "Europe/Simferopol": "RU",
  "Europe/Samara": "RU",
  "Europe/Astrakhan": "RU",
  "Europe/Volgograd": "RU",
  "Europe/Saratov": "RU",
  "Europe/Ulyanovsk": "RU",
  "Asia/Yekaterinburg": "RU",
  "Asia/Omsk": "RU",
  "Asia/Novosibirsk": "RU",
  "Asia/Barnaul": "RU",
  "Asia/Tomsk": "RU",
  "Asia/Novokuznetsk": "RU",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Irkutsk": "RU",
  "Asia/Chita": "RU",
  "Asia/Yakutsk": "RU",
  "Asia/Khandyga": "RU",
  "Asia/Vladivostok": "RU",
  "Asia/Ust-Nera": "RU",
  "Asia/Magadan": "RU",
  "Asia/Sakhalin": "RU",
  "Asia/Srednekolymsk": "RU",
  "Asia/Kamchatka": "RU",
  "Asia/Anadyr": "RU",
  "Europe/Uzhgorod": "UA",
  "Europe/Zaporozhye": "UA",
  "America/Argentina/Catamarca": "AR",
  "America/Argentina/Cordoba": "AR",
  "America/Argentina/Jujuy": "AR",
  "America/Argentina/La_Rioja": "AR",
  "America/Argentina/Mendoza": "AR",
  "America/Argentina/Rio_Gallegos": "AR",
  "America/Argentina/Salta": "AR",
  "America/Argentina/San_Juan": "AR",
  "America/Argentina/San_Luis": "AR",
  "America/Argentina/Tucuman": "AR",
  "America/Argentina/Ushuaia": "AR",
  "Asia/Urumqi": "CN",
  "Asia/Kuching": "MY",
};

export function countryCodeFromTimeZone(
  countries: Country[],
): string | undefined {
  let timeZone: string | undefined;
  try {
    timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  } catch {
    return undefined;
  }
  if (!timeZone) return undefined;

  const exact = countries.find((country) => country.timeZone === timeZone);
  if (exact) return exact.code;

  const mapped = ZONE_TO_COUNTRY[timeZone];
  if (mapped && countries.some((country) => country.code === mapped)) {
    return mapped;
  }

  return undefined;
}
